Main.class: Main.java Attribute.java Pet.java Dog.java Cat.java Mood.java Hunger.java
	javac Main.java Attribute.java Pet.java Dog.java Cat.java Mood.java Hunger.java

run: Main.class
	java Main

clean: 
	rm -f *.class

debug:
	jdb Main
